### ISSUE TITLE
ui: error occurs when clicking on an action in the analytics log

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1052]
When clicking an action in the analytics log, an error occurs in the UI.

**Comment by retini** [comment]
@gazerro, I have tried:
- creating an "Import users" action in Dummy
- writing a Javascript function in the action with an incorrect syntax
- starting the execution of the action (which results in the syntax error being bounded to the execution)
- going to the analytics section (now "metrics") and clicking on the name of the action inside the error log

The behaviour that occurs seems correct: I am redirected to the list of actions and the action in which the error occurred is automatically opened full screen.

I have investigated the code a little bit, but there do not seem to be any points where errors can occur. I do not know whether it was an error in another type of action, or whether perhaps it was resolved as a consequence of commits in the past.

Please let me know if you still encounter the error, otherwise we will consider closing the issue.

**Comment by gazerro** [comment]
I couldn't reproduce the original error, but by forcing a connector to return an error when reading users, I encountered an internal error. This doesn’t seem to be the same issue I initially reported, but I’ve fixed this other error in commit 2313a6c.

As a result, I am closing this issue.
