### ISSUE TITLE
ui: inconsistent error handling on source file action page when attempting to read records

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1058]
On the source file action page, clicking `Confirm` prompts the UI to attempt reading 20 records from the file. If a reading error occurs (e.g., a 503 error), the UI displays the error message while **still showing the remaining parts of the interface**.

Note: Reading these records is not essential; this concern may be addressed as a separate issue and could be related to issue open2b/meergo-rewritten#1032.

**Comment by retini** [comment]
@gazerro, the inconsistency in the error handling would seem to stem from the fact that when confirming the settings of a file, this call is made to the server:

```js
res = await api.workspaces.connections.records(
    connection.id,
    action.Connector,
    action.Path,
    action.Sheet === undefined ? null : action.Sheet,
    action.Compression,
    values,
    limit,
);
```
Here `limit` is set to 0, since in this context we are not interested in getting the records but only in testing that the settings entered in the action are correct.

The call you refer to, in this issue, was probably the second call to `records` that was made, namely the one to retrieve the testing mode samples. Note that from commit 3756ad6b8e1e61bd76a147db67ef274b5d84d701, this second call is now no longer made immediately after confirmation but only when opening the testing mode.

The inconsistency would therefore seem to be in the fact that the first call asked for 0 records, while the second asked for 20. This apparently causes errors to be returned on the second call that the first one does not, such as errors in the parsing of the file.

If this seems correct to you, I can make a change to the UI to ensure that calls requesting 0 records are never made (and that instead a minimum number of records is always requested, e.g. 3 records), so that potential errors when reading the file are always returned.

**Comment by gazerro** [comment]
> The inconsistency would therefore seem to be in the fact that the first call asked for 0 records, while the second asked for 20. This apparently causes errors to be returned on the second call that the first one does not, such as errors in the parsing of the file.

When a connector call causes an error, the API gives a `503 UnavailableError`. This error tells the user that something went wrong and they need to pay attention because it’s connected to something they did. For example, the file might be missing or the database might not be responding.

In this situation, when trying to read the file’s records, some checks are done, like making sure the file exists and reading the columns. These checks happen even if there are no records to read.

So, getting a `503 UnavailableError` is normal in this case, and it should just be shown to the user.

The problem is that if the user clicks `Confirm` without changing the file name, and the `503 UnavailableError` happens (maybe because the file was deleted), the rest of the interface stays editable. It should not be editable, like it is when the file path changes.

This is necessary because, since the columns could not be read (the rows don’t matter) the data shown is not correct. This would also happen if the file path changed and there was an error when confirming.

> If this seems correct to you, I can make a change to the UI to ensure that calls requesting 0 records are never made (and that instead a minimum number of records is always requested, e.g. 3 records), so that potential errors when reading the file are always returned.

As mentioned before, it is correct to send `0` as the number of records to return.
