### ISSUE TITLE
No statistics in Analytics section when importing events into the data warehouse

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1096]
## Description

I have a JavaScript connection from which I import events into the data warehouse. The events are correctly imported into the `events` table, but no statistics are reported in the "Analytics" section of the admin:

![Image](https://github.com/user-attachments/assets/b3831eb1-6382-475b-b771-9d2be744adee)

## How to reproduce the problem

1. Add a source JavaScript connection
2. Add an action that imports events into the warehouse
3. Enable the action
4. Send events
5. Verify that the events are correctly imported
6. Open the Analytics section of the admin for the JavaScript connection, which, contrary to what one might expect, contains nothing

**Comment by gazerro** [comment]
@retini we need to make the following changes to the Pipeline:

* Remove "Input validation" from the Pipeline for users received from events.
* Remove "Input validation," "Transformation," and "Output validation"; add "Filtering" for imported events.

Although not strictly part of this issue (but it is convenient to make all the changes together,) the statistics for exporting users to the database should be adjusted so that the "Filtering" step is not displayed.

**Comment by gazerro** [comment]
I am closing this issue in favor of issue open2b/meergo-rewritten#1099.
