### ISSUE TITLE
ui: event listener incorrectly set with `hasUserTraits` to `true` instead of `false`

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1128]
In the destination app event action page, an event listener is configured with `hasUserTraits` set to `true` instead of `false`. This causes only `identify` events and non-identify events containing `traits` in the `context` to be observed.

**Comment by retini** [comment]
@gazerro, I am closing this issue since commit b8148fe8f6e5ec7e461305cac42afc921e325348 has already fixed the problem.

Now the event listener that retrieves events for the testing mode of the action no longer receives `hasUserTraits`, but directly the filters. In the case of actions that export apps events the filter does not contain the condition "traits is not null", so all events are retrieved and not just the "identify" events as pointed out by this issue.

You can check the changes in the file `assets/src/components/routes/ActionWrapper/ActionTransformation.tsx` directly in the [commit](https://github.com/open2b/meergo/commit/b8148fe8f6e5ec7e461305cac42afc921e325348) (I do not post the direct link because it does not seem to work in Github).
