### ISSUE TITLE
Cannot read column `PhoneNumbers` from data warehouse

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#208]
When reading users from the database using the method:

https://github.com/open2b/chichi/blob/e5128ea8b6339ec7c5f3cce62faf6226674a293e/apis/workspace.go#L990

if the data warehouse contains a not-null value in the column:

https://github.com/open2b/chichi/blob/d171b4fbf20a43efb5e89bbf0e6012a085b76325/database/warehouses/postgresql.sql#L31

then the driver returns the error:

```json
{"error":{"code":"WarehouseFailed","message":"warehouse connection is failed: can't scan into dest[3]: database returned a value of '0' for column PhoneNumbers, but it cannot be converted to the Text type","cause":"can't scan into dest[3]: database returned a value of '0' for column PhoneNumbers, but it cannot be converted to the Text type"}}
```

**Comment by gazerro** [comment]
Arrays in PostgreSQL are not supported when PostgreSQL is used as data warehouse. When used as the main database, at least for basic data types, arrays are supported.

When PostgreSQL returns array values, it returns a `[]byte` value (particularly for arrays of type `text[]`) with a binary encoding.

The key difference between using PostgreSQL as a data warehouse and as the main database lies in the type of argument passed to the `Scan` function when reading a value from an Array-type column. In the case of the data warehouse, the argument for the `Scan` function is of type `warehouses.ScanValue`, and the scan invokes the `warehouses.ScanValue.Scan` method to handle the value scanning. On the other hand, when using PostgreSQL as the main database, the argument has a specific Go array type tailored for the value to be serialized. For instance, the value to be serialized is of type `varchar[]` and the Go type used for the argument is `[]string`. In this case, the `Scan` method directly utilizes the `pgx` driver functions to deserialize the arrays.

The root of the issue lies in the `warehouses.ScanValue.Scan` method, which directly calls the function `normalizations.NormalizeDatabaseFileProperty`. However, this function does not expect a `[]byte` value, which is what PostgreSQL returns for arrays, as array normalization for PostgreSQL is not supported (refer to: https://github.com/open2b/chichi/blob/main/apis/Data_Types.md). Consequently, this can be considered an error within the `Tables` method of the PostgreSQL data warehouse driver, as it should ideally return an error when a column has an array type.

On the other hand, the functions within the `pgx` package handle array deserialization directly, at least for certain types of arrays (see: https://github.com/jackc/pgx/blob/master/pgtype/array.go).
