### ISSUE TITLE
connectors/csv: specify the behaviour when importing file with empty cells

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#254]
Consider this CSV:

```csv
CustomerID,Email
ABC,
EDF,2@example.com
```

since the `Email` is missing for the first row, when this CSV is imported, should the user be without an `Email`, or should have the `Email` with an empty string value?

This makes difference both in the _identity resolution_ process as well as when updating the user on the data warehouse.

This may also apply to other file formats when importing.

**Comment by gazerro** [comment]
As discussed with @zapateo, it is essential for a connector to return a value for all properties, and this returned value must adhere to the schema defined by the connector.

Specifically concerning the "csv" connector, we do not discern any practical advantage between returning an empty string and returning `nil`. However, if the decision is to return `nil`, it should be properly documented. On the other hand, when returning an empty string, documentation may not be necessary. Therefore, it is preferable for the "csv" connector to return an empty string rather than `nil`.
