### ISSUE TITLE
connectors/excel: misleading error displayed when reading an Excel file

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#345]
![image](https://github.com/open2b/meergo-rewritten/assets/53836466/5b82e3c5-c6cc-458b-84fc-0d4e0e5fcdf9)

## Steps to reproduce

1. Add an Excel (destination or source) connection, with a filesystem storage
2. Click on "Add action…" and select one of the actions
3. In the "Path" field insert the name of the corrupted Excel file
4. Click on the "Sheet" select

## Problems

The error `zip: not a valid zip file` is always returned when trying to fetch the sheets of a corrupted Excel file inside the action creation page, even if during the creation of the connection the value for the "Compression" field is set to "None".

The error is misleading and doesn't help understanding what the underlying problem is.

**Comment by gazerro** [comment]
The XSLX file format is essentially a compressed ZIP file. Therefore, in the connection, if it's indicated that the file isn't compressed, the connector will directly read the file using the "archive/zip" package. Since the file is corrupted, it returns the reported error.

However, if it's specified in the connection that the file is compressed in ZIP format, then ChiChi will first attempt to decompress the file. ChiChi uses the same package as the connector to do this, resulting in the same error.

I believe we should display two types of errors. In the first case the connector should replace the "zip: zip: not a valid zip file" error with a "not a valid Excel (.xlsx) file" error, and ChiChi should decorate the error message:

"Unable to read the file: not a valid Excel (.xlsx) file"

And in the second case, ChiChi should return:

"Unable to decompress the ZIP-format file: zip: not a valid zip file"

**Comment by gazerro** [comment]
@retini I believe commit 8c1da18 has resolved the issue. Can you confirm?

**Comment by retini** [comment]
@gazerro, yes, I confirm
