### ISSUE TITLE
import: don't allow to create an action with invalid schemas

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#457]
## Description

In the issue https://github.com/open2b/chichi/issues/230 we decided that import actions with no mapped properties should be illegal. Currently, in Chichi, it is possible to create such kind of actions, and when running them an error `output schema is not valid` is returned.

~We should add some checks where necessary, in order to return clearer error messages.~
We should returns a bad request error when creating an action with invalid schemas.

## Steps to reproduce

1. Add a Dummy source connection
2. Create a users import action with no mapped properties
3. Run the action

**Comment by gazerro** [comment]
The commit c62853c has ensured to return an internal error instead of "output schema is not valid" since it is an internal error.

**Comment by gazerro** [comment]
@zapateo ~While doing step 2, Chichi returns the error 'mapping (or transformation) is required,' making it impossible to proceed to step 3.~

**Comment by gazerro** [comment]
After the commit 5c56133, the server returns a bad request error with the message "transformation mapping or function is required" if no mapping or function has been set for the transformation.

This commit ensures that importing a non-nil but empty mapping is no longer possible. Consequently, the UI now sends a `nil` mapping and function to the server when no transformation is set.

To resolve this issue completely, the missing part is to make the UI display an error message instead of sending a `nil` mapping and function to the server.

**Comment by gazerro** [comment]
@retini Could you look at this part?

> To resolve this issue completely, the missing part is to make the UI display an error message instead of sending a nil mapping and function to the server.

**Comment by retini** [comment]
Commit [`6f24bfb`](https://github.com/open2b/chichi/commit/6f24bfb5fb724550b8c08e169abff9e3bd947404) ensures that the UI shows an error message when the user tries to save an action with empty mappings
