### ISSUE TITLE
export: review the ordering of the exported users

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#757]
<details>
<summary>Outdated</summary>
## Current Situation

Currently, when users are exported, they are read and sorted by `properties[0]`, that is the first of the properties to export. This is just a temporary workaround.

## What We Should Do

Discuss what should be the property for sorting users.
</details>

**Comment by gazerro** [comment]
Does the order in which users are exported affect the final export outcome? Some points to consider:

* For files, I might expect the user in the action to be able to choose how users should be ordered in the file.
* For databases, the order shouldn't matter.
* For apps, it shouldn't matter either, but what happens if multiple users in Chichi map to the same user in the app? Could the export order affect the final value present in the app user?

**Comment by zapateo** [comment]
After a discussion with @gazerro, we decided that:

* For files, we could add a setting in the action to choose the sorting. Maybe we put a default.
* For databases, do not sort.
* For apps, don't sort by this either.
