### ISSUE TITLE
Renaming a property in user schema breaks schema alignment and UI

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#863]
How to reproduce:

1. Create an action with a mapping to property "a".
2. Rename this property from "a" to "b" in the user schema.
3. Open the action in the UI.

Expected result: Property "b" should be mapped with the same expression previously used for "a".

Actual result: Neither property "a" nor property "b" is visible.

**Comment by zapateo** [comment]
After a discussion with @gazerro, we have established that the problem is broader and that it also concerns the alignment of the schemas in general when a property is renamed.

Some notes:

* When renaming a property of the user schema, the properties in the mappings and in the action schema must be renamed, both when importing and when exporting
* For transformations there is little to do. At most we could inform the user that these actions will stop working, and require manual intervention.

**Comment by zapateo** [comment]
@gazerro, we should revisit this issue in light of recent changes to the concept of “alignment”.

**Comment by zapateo** [comment]
## Discussion 2024/07/11

After a discussion with @gazerro, we came to the following conclusions.

### For IR identifiers

Changes to comply with the principle that "IR identifiers must be properties of the user schema":

* [x] When a schema property is renamed, the corresponding identifier is renamed, if any
* [x] When a schema property is deleted, the corresponding identifier is deleted, if any

The "opposite side" - when the identifiers of the workspace are set - is discussed in issue open2b/meergo-rewritten#803.

**Comment by gazerro** [comment]
Some aspects of this issue related to usability have been moved to issue open2b/meergo-rewritten#930. Therefore, I am closing this issue as resolved.
